# Generated by Django 4.2.7 on 2025-11-21 07:39

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConstructionProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('description', models.TextField(verbose_name='Description')),
                ('progress_percentage', models.IntegerField(help_text='Progress from 0 to 100%', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Progress Percentage')),
                ('update_date', models.DateField(verbose_name='Update Date')),
                ('image', models.ImageField(blank=True, null=True, upload_to='construction_progress/', verbose_name='Image')),
                ('is_published', models.BooleanField(default=True, verbose_name='Published')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_updates', to='properties.project', verbose_name='Project')),
            ],
            options={
                'verbose_name': 'Construction Progress',
                'verbose_name_plural': 'Construction Progress Updates',
                'ordering': ['-update_date', '-created_at'],
            },
        ),
        migrations.AlterField(
            model_name='property',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('new_offer', 'New Offer'), ('sold', 'Sold'), ('booked', 'Booked'), ('on_hold', 'On Hold')], default='active', max_length=20),
        ),
        migrations.CreateModel(
            name='PropertyBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('expired', 'Expired'), ('completed', 'Completed')], default='pending', max_length=20, verbose_name='Status')),
                ('start_date', models.DateTimeField(verbose_name='Start Date')),
                ('end_date', models.DateTimeField(verbose_name='End Date')),
                ('full_name', models.CharField(max_length=200, verbose_name='Full Name')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone', models.CharField(max_length=20, verbose_name='Phone')),
                ('id_number', models.CharField(blank=True, max_length=50, verbose_name='ID Number')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('admin_notes', models.TextField(blank=True, verbose_name='Admin Notes')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='Approved At')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_bookings', to=settings.AUTH_USER_MODEL, verbose_name='Approved By')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='properties.property', verbose_name='Property')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='property_bookings', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Property Booking',
                'verbose_name_plural': 'Property Bookings',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ConstructionProgressImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='construction_progress/images/', verbose_name='Image')),
                ('caption', models.CharField(blank=True, max_length=200, verbose_name='Caption')),
                ('order', models.IntegerField(default=0, verbose_name='Order')),
                ('progress', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='properties.constructionprogress', verbose_name='Progress Update')),
            ],
            options={
                'verbose_name': 'Progress Image',
                'verbose_name_plural': 'Progress Images',
                'ordering': ['order'],
            },
        ),
    ]
