# Generated by Django 4.2.7 on 2025-11-22 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0002_constructionprogress_alter_property_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomePageSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_video', models.FileField(blank=True, help_text='Video file for homepage hero section (MP4 recommended)', null=True, upload_to='videos/homepage/', verbose_name='Hero Video')),
                ('hero_video_poster', models.ImageField(blank=True, help_text='Poster image shown before video loads', null=True, upload_to='images/homepage/', verbose_name='Video Poster Image')),
                ('hero_video_enabled', models.BooleanField(default=True, help_text='Enable/disable video background', verbose_name='Video Enabled')),
                ('hero_title', models.CharField(default='MAKE YOUR NEXT MOVE WITH US', max_length=200, verbose_name='Hero Title')),
                ('hero_subtitle', models.CharField(default='ANDROMEDA PROPERTIES', max_length=200, verbose_name='Hero Subtitle')),
                ('hero_description', models.TextField(blank=True, default='Discover the latest real estate in Ethiopia on Andromeda Properties', max_length=500, verbose_name='Hero Description')),
                ('hero_button_text', models.CharField(default='Explore Properties', max_length=50, verbose_name='Hero Button Text')),
                ('use_static_video', models.BooleanField(default=True, help_text='Use static video (video104.mp4) if no video is uploaded', verbose_name='Use Static Video Fallback')),
                ('static_video_path', models.CharField(default='videos/video104.mp4', help_text='Path to static video file (relative to static folder)', max_length=200, verbose_name='Static Video Path')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'Homepage Settings',
                'verbose_name_plural': 'Homepage Settings',
            },
        ),
    ]
