# Generated by Django 4.2.7 on 2025-11-24 06:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0003_homepagesettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('whatsapp_number', models.CharField(blank=True, help_text='WhatsApp Business number with country code (e.g., +251912345678)', max_length=20, verbose_name='WhatsApp Number')),
                ('whatsapp_default_message', models.CharField(default='Hello! I am interested in your properties.', help_text='Default message for WhatsApp inquiries', max_length=500, verbose_name='Default WhatsApp Message')),
                ('whatsapp_enabled', models.BooleanField(default=True, help_text='Enable WhatsApp floating button', verbose_name='WhatsApp Enabled')),
                ('company_phone', models.CharField(blank=True, max_length=20, verbose_name='Company Phone')),
                ('company_email', models.EmailField(blank=True, max_length=254, verbose_name='Company Email')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'Site Settings',
                'verbose_name_plural': 'Site Settings',
            },
        ),
        migrations.AddField(
            model_name='property',
            name='is_verified',
            field=models.BooleanField(default=False, help_text='Mark property as verified for trust building', verbose_name='Verified'),
        ),
        migrations.AddField(
            model_name='teammember',
            name='is_verified',
            field=models.BooleanField(default=False, help_text='Mark agent as verified', verbose_name='Verified'),
        ),
        migrations.AddField(
            model_name='teammember',
            name='languages',
            field=models.CharField(blank=True, help_text='Languages spoken (comma-separated, e.g., English, Amharic, Arabic)', max_length=200, verbose_name='Languages'),
        ),
        migrations.AddField(
            model_name='teammember',
            name='whatsapp_number',
            field=models.CharField(blank=True, help_text='WhatsApp number with country code (e.g., +251912345678)', max_length=20, verbose_name='WhatsApp Number'),
        ),
        migrations.AddField(
            model_name='teammember',
            name='years_experience',
            field=models.IntegerField(default=0, help_text='Years of experience in real estate', verbose_name='Years of Experience'),
        ),
        migrations.CreateModel(
            name='ViewingAppointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200, verbose_name='Full Name')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone', models.CharField(max_length=20, verbose_name='Phone')),
                ('whatsapp_number', models.CharField(blank=True, help_text='WhatsApp number if different from phone', max_length=20, verbose_name='WhatsApp Number')),
                ('preferred_date', models.DateField(verbose_name='Preferred Date')),
                ('preferred_time', models.TimeField(verbose_name='Preferred Time')),
                ('notes', models.TextField(blank=True, verbose_name='Additional Notes')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('assigned_agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='viewing_appointments', to='properties.teammember', verbose_name='Assigned Agent')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='viewing_appointments', to='properties.property', verbose_name='Property')),
            ],
            options={
                'verbose_name': 'Viewing Appointment',
                'verbose_name_plural': 'Viewing Appointments',
                'ordering': ['-created_at'],
            },
        ),
    ]
