# Generated by Django 4.2.7 on 2025-11-24 07:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0004_sitesettings_property_is_verified_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='walkthrough_video',
            field=models.FileField(blank=True, help_text='Video walkthrough of the property (MP4 recommended)', null=True, upload_to='properties/videos/', verbose_name='Video Walkthrough'),
        ),
        migrations.AddField(
            model_name='property',
            name='walkthrough_video_url',
            field=models.URLField(blank=True, help_text='YouTube or Vimeo video URL (alternative to uploaded video)', null=True, verbose_name='Video URL'),
        ),
        migrations.CreateModel(
            name='FloorPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='properties/floor_plans/', verbose_name='Floor Plan Image')),
                ('title', models.CharField(blank=True, help_text='e.g., "Ground Floor", "First Floor", "Unit Layout"', max_length=200, verbose_name='Title')),
                ('description', models.TextField(blank=True, help_text='Description of this floor plan', verbose_name='Description')),
                ('order', models.IntegerField(default=0, help_text='Display order (lower numbers appear first)', verbose_name='Order')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='floor_plans', to='properties.property', verbose_name='Property')),
            ],
            options={
                'verbose_name': 'Floor Plan',
                'verbose_name_plural': 'Floor Plans',
                'ordering': ['order', 'created_at'],
            },
        ),
    ]
