# Generated by Django 4.2.7 on 2025-11-24 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0005_property_walkthrough_video_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BuyingGuide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug')),
                ('category', models.CharField(choices=[('first_time_buyer', 'First-Time Buyer'), ('investment', 'Investment Guide'), ('financing', 'Financing Guide'), ('legal', 'Legal Guide'), ('tips', 'Tips & Advice'), ('other', 'Other')], default='tips', max_length=50, verbose_name='Category')),
                ('excerpt', models.TextField(blank=True, help_text='Short summary for listings', max_length=500, verbose_name='Excerpt')),
                ('content', models.TextField(verbose_name='Content')),
                ('featured_image', models.ImageField(blank=True, null=True, upload_to='buying_guides/', verbose_name='Featured Image')),
                ('tags', models.CharField(blank=True, help_text='Comma-separated tags for SEO', max_length=300, verbose_name='Tags')),
                ('is_published', models.BooleanField(default=True, verbose_name='Published')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Featured')),
                ('view_count', models.IntegerField(default=0, verbose_name='View Count')),
                ('publication_date', models.DateField(verbose_name='Publication Date')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'Buying Guide',
                'verbose_name_plural': 'Buying Guides',
                'ordering': ['-publication_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MarketReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug')),
                ('excerpt', models.TextField(blank=True, help_text='Short summary for listings', max_length=500, verbose_name='Excerpt')),
                ('content', models.TextField(verbose_name='Content')),
                ('featured_image', models.ImageField(blank=True, null=True, upload_to='market_reports/', verbose_name='Featured Image')),
                ('pdf_file', models.FileField(blank=True, help_text='Optional PDF download', null=True, upload_to='market_reports/pdfs/', verbose_name='PDF File')),
                ('category', models.CharField(blank=True, help_text='e.g., "Q1 2025", "Annual Report", "Market Analysis"', max_length=100, verbose_name='Category')),
                ('tags', models.CharField(blank=True, help_text='Comma-separated tags for SEO', max_length=300, verbose_name='Tags')),
                ('is_published', models.BooleanField(default=True, verbose_name='Published')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Featured')),
                ('view_count', models.IntegerField(default=0, verbose_name='View Count')),
                ('publication_date', models.DateField(verbose_name='Publication Date')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'Market Report',
                'verbose_name_plural': 'Market Reports',
                'ordering': ['-publication_date', '-created_at'],
            },
        ),
        migrations.AddField(
            model_name='property',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Latitude for map display (e.g., 9.1450)', max_digits=9, null=True, verbose_name='Latitude'),
        ),
        migrations.AddField(
            model_name='property',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Longitude for map display (e.g., 38.7614)', max_digits=9, null=True, verbose_name='Longitude'),
        ),
    ]
