# Generated by Django 4.2.7 on 2025-11-26 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0006_buyingguide_marketreport_property_latitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='virtual_tour_image',
            field=models.ImageField(blank=True, help_text='360-degree panoramic image for virtual tour (equirectangular format recommended)', null=True, upload_to='properties/virtual_tours/', verbose_name='Virtual Tour Image'),
        ),
        migrations.AddField(
            model_name='property',
            name='virtual_tour_url',
            field=models.URLField(blank=True, help_text='External virtual tour URL (e.g., Matterport, Kuula, etc.)', null=True, verbose_name='Virtual Tour URL'),
        ),
    ]
