# Generated by Django 5.2.8 on 2025-12-01 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0007_property_virtual_tour_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutPageSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about_video', models.FileField(blank=True, help_text='Video file for about page (MP4 recommended)', null=True, upload_to='videos/about/', verbose_name='About Page Video')),
                ('about_video_url', models.URLField(blank=True, help_text='External video URL (YouTube, Vimeo, etc.)', null=True, verbose_name='Video URL')),
                ('about_video_poster', models.ImageField(blank=True, help_text='Poster image shown before video loads', null=True, upload_to='images/about/', verbose_name='Video Poster Image')),
                ('about_video_enabled', models.BooleanField(default=True, help_text='Enable/disable video display', verbose_name='Video Enabled')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'About Page Settings',
                'verbose_name_plural': 'About Page Settings',
            },
        ),
    ]
