# Generated by Django 5.2.8 on 2025-12-25 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0008_aboutpagesettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='PromotionalOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Title')),
                ('description', models.CharField(max_length=200, verbose_name='Description')),
                ('icon', models.CharField(choices=[('target', 'Target/Discount'), ('money', 'Money/Finance'), ('gift', 'Gift'), ('star', 'Star'), ('tag', 'Tag')], default='target', max_length=20, verbose_name='Icon')),
                ('badge_type', models.CharField(choices=[('hot_deal', 'Hot Deal'), ('new', 'New'), ('limited', 'Limited'), ('sale', 'Sale')], default='hot_deal', max_length=20, verbose_name='Badge Type')),
                ('badge_color', models.CharField(default='primary', help_text='Bootstrap color class: primary, success, warning, danger, info', max_length=20, verbose_name='Badge Color')),
                ('icon_color', models.CharField(default='info', help_text='Bootstrap color class for icon background', max_length=20, verbose_name='Icon Color')),
                ('call_action_text', models.CharField(default='Call Now', max_length=50, verbose_name='Call Action Text')),
                ('call_action_url', models.CharField(blank=True, help_text='Phone number (e.g., +251913677468) or URL', max_length=200, verbose_name='Call Action URL/Phone')),
                ('details_action_text', models.CharField(default='Get Details', max_length=50, verbose_name='Details Action Text')),
                ('details_action_url', models.URLField(blank=True, null=True, verbose_name='Details Action URL')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('order', models.IntegerField(default=0, verbose_name='Order')),
                ('start_date', models.DateTimeField(blank=True, null=True, verbose_name='Start Date')),
                ('end_date', models.DateTimeField(blank=True, null=True, verbose_name='End Date')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'Promotional Offer',
                'verbose_name_plural': 'Promotional Offers',
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.RemoveField(
            model_name='property',
            name='virtual_tour_image',
        ),
        migrations.RemoveField(
            model_name='property',
            name='virtual_tour_url',
        ),
    ]
