# Generated by Django 5.2.8 on 2025-12-25 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0009_promotionaloffer_remove_property_virtual_tour_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='virtual_tour_image',
            field=models.ImageField(blank=True, help_text='360-degree panoramic image for virtual tour (equirectangular format recommended)', null=True, upload_to='properties/virtual_tours/', verbose_name='Virtual Tour Image'),
        ),
        migrations.AddField(
            model_name='property',
            name='virtual_tour_url',
            field=models.URLField(blank=True, help_text='External virtual tour URL (e.g., Matterport, Kuula, etc.)', null=True, verbose_name='Virtual Tour URL'),
        ),
    ]
