# Generated by Django 5.2.8 on 2025-12-26 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0010_property_virtual_tour_image_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AboutPageSettings',
        ),
        migrations.DeleteModel(
            name='PromotionalOffer',
        ),
        migrations.RemoveField(
            model_name='property',
            name='virtual_tour_image',
        ),
        migrations.RemoveField(
            model_name='property',
            name='virtual_tour_url',
        ),
    ]
