# Generated by Django 5.2.8 on 2025-12-26 13:56

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0011_delete_aboutpagesettings_delete_promotionaloffer_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PromotionalOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('description', models.TextField(verbose_name='Description')),
                ('icon', models.CharField(choices=[('target', 'Target'), ('money', 'Money'), ('gift', 'Gift'), ('star', 'Star'), ('tag', 'Tag')], default='star', max_length=20, verbose_name='Icon')),
                ('icon_color', models.CharField(choices=[('primary', 'Primary'), ('success', 'Success'), ('danger', 'Danger'), ('warning', 'Warning'), ('info', 'Info')], default='primary', max_length=20, verbose_name='Icon Color')),
                ('badge_type', models.CharField(choices=[('hot_deal', 'Hot Deal'), ('new', 'New'), ('limited', 'Limited'), ('sale', 'Sale')], default='new', max_length=20, verbose_name='Badge Type')),
                ('badge_color', models.CharField(choices=[('primary', 'Primary'), ('success', 'Success'), ('danger', 'Danger'), ('warning', 'Warning'), ('info', 'Info')], default='danger', max_length=20, verbose_name='Badge Color')),
                ('call_action_text', models.CharField(blank=True, help_text='Text for call action button (e.g., "Call Now")', max_length=100, verbose_name='Call Action Text')),
                ('call_action_url', models.CharField(blank=True, help_text='Phone number or URL for call action (e.g., "tel:+251912345678" or URL)', max_length=200, verbose_name='Call Action URL')),
                ('details_action_text', models.CharField(blank=True, help_text='Text for details action button (e.g., "View Details")', max_length=100, verbose_name='Details Action Text')),
                ('details_action_url', models.URLField(blank=True, help_text='URL for details action (e.g., property detail page)', null=True, verbose_name='Details Action URL')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('order', models.IntegerField(default=0, help_text='Display order (lower numbers appear first)', verbose_name='Order')),
                ('start_date', models.DateField(blank=True, help_text='Start date for the offer (leave blank for immediate start)', null=True, verbose_name='Start Date')),
                ('end_date', models.DateField(blank=True, help_text='End date for the offer (leave blank for no expiration)', null=True, verbose_name='End Date')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'Promotional Offer',
                'verbose_name_plural': 'Promotional Offers',
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='constructionprogressimage',
            options={'ordering': ['order']},
        ),
        migrations.AlterModelOptions(
            name='floorplan',
            options={'ordering': ['order']},
        ),
        migrations.AlterModelOptions(
            name='propertybooking',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='constructionprogress',
            name='image',
        ),
        migrations.RemoveField(
            model_name='floorplan',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='marketreport',
            name='pdf_file',
        ),
        migrations.AlterField(
            model_name='buyingguide',
            name='category',
            field=models.CharField(choices=[('tips', 'Buying Tips'), ('financing', 'Financing'), ('legal', 'Legal Advice'), ('investment', 'Investment Guide'), ('general', 'General')], default='tips', max_length=50, verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='constructionprogress',
            name='progress_percentage',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Progress Percentage'),
        ),
        migrations.AlterField(
            model_name='constructionprogressimage',
            name='caption',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='constructionprogressimage',
            name='image',
            field=models.ImageField(upload_to='construction_progress/'),
        ),
        migrations.AlterField(
            model_name='constructionprogressimage',
            name='order',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='constructionprogressimage',
            name='progress',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='properties.constructionprogress'),
        ),
        migrations.AlterField(
            model_name='floorplan',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='floorplan',
            name='image',
            field=models.ImageField(upload_to='properties/floor_plans/'),
        ),
        migrations.AlterField(
            model_name='floorplan',
            name='order',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='floorplan',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='floor_plans', to='properties.property'),
        ),
        migrations.AlterField(
            model_name='floorplan',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='marketreport',
            name='category',
            field=models.CharField(choices=[('market_analysis', 'Market Analysis'), ('price_trends', 'Price Trends'), ('location_insights', 'Location Insights'), ('investment_advice', 'Investment Advice'), ('general', 'General')], default='general', max_length=50, verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='propertybooking',
            name='admin_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='propertybooking',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='propertybooking',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_bookings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='propertybooking',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='propertybooking',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='propertybooking',
            name='end_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='propertybooking',
            name='full_name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='propertybooking',
            name='id_number',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='propertybooking',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='propertybooking',
            name='phone',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='propertybooking',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='properties.property'),
        ),
        migrations.AlterField(
            model_name='propertybooking',
            name='start_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='propertybooking',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='propertybooking',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='propertybooking',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='property_bookings', to=settings.AUTH_USER_MODEL),
        ),
    ]
