# Generated by Django 5.2.8 on 2025-12-26 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0012_promotionaloffer_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutPageSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about_video_enabled', models.BooleanField(default=True, help_text='Enable/disable video on about page', verbose_name='Video Enabled')),
                ('about_video', models.FileField(blank=True, help_text='Video file for about page (MP4 recommended)', null=True, upload_to='videos/about/', verbose_name='About Video')),
                ('about_video_url', models.URLField(blank=True, help_text='YouTube or Vimeo video URL (alternative to uploaded video)', null=True, verbose_name='Video URL')),
                ('about_video_poster', models.ImageField(blank=True, help_text='Poster image shown before video loads', null=True, upload_to='images/about/', verbose_name='Video Poster Image')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'About Page Settings',
                'verbose_name_plural': 'About Page Settings',
            },
        ),
    ]
