# Generated by Django 5.2.8 on 2026-02-04 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0013_aboutpagesettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyNeedRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150, verbose_name='Full Name')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=30, verbose_name='Phone')),
                ('whatsapp_number', models.CharField(blank=True, max_length=30, verbose_name='WhatsApp Number')),
                ('preferred_location', models.CharField(blank=True, max_length=200, verbose_name='Preferred Location')),
                ('property_type', models.CharField(blank=True, choices=[('apartment', 'Apartment'), ('shop', 'Shop'), ('commercial', 'Commercial')], max_length=30, verbose_name='Property Type')),
                ('sale_type', models.CharField(blank=True, choices=[('for_sale', 'Financed with bank'), ('for_rent', 'Non financed with bank')], max_length=30, verbose_name='Sale/Payment Type')),
                ('bedrooms_min', models.IntegerField(blank=True, null=True, verbose_name='Min Bedrooms')),
                ('bedrooms_max', models.IntegerField(blank=True, null=True, verbose_name='Max Bedrooms')),
                ('bathrooms_min', models.IntegerField(blank=True, null=True, verbose_name='Min Bathrooms')),
                ('bathrooms_max', models.IntegerField(blank=True, null=True, verbose_name='Max Bathrooms')),
                ('budget_min', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Min Budget (ETB)')),
                ('budget_max', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Max Budget (ETB)')),
                ('size_min', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Min Size (m²)')),
                ('size_max', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Max Size (m²)')),
                ('move_in_timeline', models.CharField(blank=True, max_length=100, verbose_name='Preferred Move-in Timeline')),
                ('notes', models.TextField(blank=True, verbose_name='Additional Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Submitted At')),
            ],
            options={
                'verbose_name': 'Property Need Request',
                'verbose_name_plural': 'Property Need Requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterField(
            model_name='property',
            name='sale_type',
            field=models.CharField(choices=[('for_sale', 'Financed with bank'), ('for_rent', 'Non financed with bank')], default='for_sale', max_length=20),
        ),
    ]
