# Generated by Django 5.2.14 on 2026-06-11 19:32

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0014_propertyneedrequest_alter_property_sale_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaseStudy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug')),
                ('client_name', models.CharField(max_length=200, verbose_name='Client Name')),
                ('industry', models.CharField(blank=True, max_length=100, verbose_name='Industry')),
                ('challenge', models.TextField(verbose_name='Challenge')),
                ('solution', models.TextField(verbose_name='Solution')),
                ('results', models.TextField(verbose_name='Results')),
                ('excerpt', models.TextField(blank=True, max_length=500, verbose_name='Excerpt')),
                ('featured_image', models.ImageField(blank=True, null=True, upload_to='case_studies/', verbose_name='Featured Image')),
                ('project_start', models.DateField(blank=True, null=True, verbose_name='Project Start')),
                ('project_end', models.DateField(blank=True, null=True, verbose_name='Project End')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Featured')),
                ('is_published', models.BooleanField(default=True, verbose_name='Published')),
                ('order', models.IntegerField(default=0, verbose_name='Display Order')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Case Study',
                'verbose_name_plural': 'Case Studies',
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MediaAlbum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='gallery/covers/', verbose_name='Cover Image')),
                ('category', models.CharField(blank=True, max_length=100, verbose_name='Category')),
                ('is_published', models.BooleanField(default=True, verbose_name='Published')),
                ('order', models.IntegerField(default=0, verbose_name='Display Order')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Media Album',
                'verbose_name_plural': 'Media Albums',
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Milestone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=20, verbose_name='Year')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('description', models.TextField(verbose_name='Description')),
                ('order', models.IntegerField(default=0, verbose_name='Display Order')),
            ],
            options={
                'verbose_name': 'Milestone',
                'verbose_name_plural': 'Milestones',
                'ordering': ['order', 'year'],
            },
        ),
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='partners/', verbose_name='Logo')),
                ('website', models.URLField(blank=True, verbose_name='Website')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('order', models.IntegerField(default=0, verbose_name='Display Order')),
            ],
            options={
                'verbose_name': 'Partner',
                'verbose_name_plural': 'Partners',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug')),
                ('category', models.CharField(choices=[('management_consultancy', 'Management Consultancy'), ('strategic_leadership', 'Strategic Leadership'), ('hr_sourcing', 'HR Sourcing'), ('investment', 'Investment'), ('organizational_development', 'Organizational Development')], max_length=50, verbose_name='Category')),
                ('short_description', models.TextField(max_length=500, verbose_name='Short Description')),
                ('full_description', models.TextField(verbose_name='Full Description')),
                ('icon', models.CharField(default='bi-briefcase', help_text='Bootstrap icon class (e.g., bi-briefcase)', max_length=50, verbose_name='Icon')),
                ('image', models.ImageField(blank=True, null=True, upload_to='services/', verbose_name='Image')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Featured')),
                ('order', models.IntegerField(default=0, verbose_name='Display Order')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Service',
                'verbose_name_plural': 'Services',
                'ordering': ['order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=100, verbose_name='Client Name')),
                ('organization', models.CharField(blank=True, max_length=200, verbose_name='Organization')),
                ('position', models.CharField(blank=True, max_length=100, verbose_name='Position')),
                ('content', models.TextField(verbose_name='Testimonial')),
                ('image', models.ImageField(blank=True, null=True, upload_to='testimonials/', verbose_name='Photo')),
                ('rating', models.IntegerField(default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Rating')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Featured')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('order', models.IntegerField(default=0, verbose_name='Display Order')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Testimonial',
                'verbose_name_plural': 'Testimonials',
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TrainingEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug')),
                ('event_type', models.CharField(choices=[('training', 'Training Program'), ('workshop', 'Workshop'), ('seminar', 'Seminar'), ('conference', 'Conference'), ('consultancy', 'Consultancy Session')], default='training', max_length=30)),
                ('description', models.TextField(verbose_name='Description')),
                ('short_description', models.TextField(blank=True, max_length=500, verbose_name='Short Description')),
                ('start_date', models.DateTimeField(verbose_name='Start Date')),
                ('end_date', models.DateTimeField(verbose_name='End Date')),
                ('location', models.CharField(max_length=200, verbose_name='Location')),
                ('venue', models.CharField(blank=True, max_length=200, verbose_name='Venue')),
                ('max_participants', models.IntegerField(default=50, verbose_name='Max Participants')),
                ('registration_deadline', models.DateTimeField(blank=True, null=True, verbose_name='Registration Deadline')),
                ('brochure', models.FileField(blank=True, help_text='Downloadable brochure (PDF)', null=True, upload_to='brochures/', verbose_name='Brochure')),
                ('featured_image', models.ImageField(blank=True, null=True, upload_to='events/', verbose_name='Featured Image')),
                ('is_published', models.BooleanField(default=True, verbose_name='Published')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Featured')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Training Event',
                'verbose_name_plural': 'Training Events',
                'ordering': ['start_date'],
            },
        ),
        migrations.CreateModel(
            name='WorkingSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')], unique=True, verbose_name='Day')),
                ('open_time', models.TimeField(blank=True, null=True, verbose_name='Open Time')),
                ('close_time', models.TimeField(blank=True, null=True, verbose_name='Close Time')),
                ('is_closed', models.BooleanField(default=False, verbose_name='Closed')),
            ],
            options={
                'verbose_name': 'Working Schedule',
                'verbose_name_plural': 'Working Schedules',
                'ordering': ['day_of_week'],
            },
        ),
        migrations.AlterModelOptions(
            name='teammember',
            options={'ordering': ['order', 'name']},
        ),
        migrations.AddField(
            model_name='homepagesettings',
            name='hero_button_url',
            field=models.CharField(default='/services/', max_length=200, verbose_name='Hero Button URL'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='company_address',
            field=models.CharField(blank=True, max_length=300, verbose_name='Company Address'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='company_name',
            field=models.CharField(default='Team Training and Consultancy Service PLC', max_length=200, verbose_name='Company Name'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='company_phone_secondary',
            field=models.CharField(blank=True, max_length=50, verbose_name='Secondary Phone'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='company_tagline',
            field=models.CharField(default='Guiding your Success, Every step of the way!', max_length=200, verbose_name='Company Tagline'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Latitude for map (e.g., 8.5400)', max_digits=9, null=True, verbose_name='Latitude'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Longitude for map (e.g., 39.2700)', max_digits=9, null=True, verbose_name='Longitude'),
        ),
        migrations.AddField(
            model_name='teammember',
            name='credentials',
            field=models.TextField(blank=True, help_text='Degrees, certifications, and professional credentials', verbose_name='Credentials'),
        ),
        migrations.AddField(
            model_name='teammember',
            name='is_founder',
            field=models.BooleanField(default=False, verbose_name='Founder'),
        ),
        migrations.AddField(
            model_name='teammember',
            name='order',
            field=models.IntegerField(default=0, verbose_name='Display Order'),
        ),
        migrations.AddField(
            model_name='teammember',
            name='title',
            field=models.CharField(blank=True, help_text='Professional title or designation', max_length=200, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='homepagesettings',
            name='hero_button_text',
            field=models.CharField(default='Explore Our Services', max_length=50, verbose_name='Hero Button Text'),
        ),
        migrations.AlterField(
            model_name='homepagesettings',
            name='hero_description',
            field=models.TextField(blank=True, default='Specialized training, consultancy, and human resource sourcing solutions tailored to enhance organizational effectiveness and employee development.', max_length=500, verbose_name='Hero Description'),
        ),
        migrations.AlterField(
            model_name='homepagesettings',
            name='hero_subtitle',
            field=models.CharField(default='TEAM TRAINING AND CONSULTANCY SERVICE PLC', max_length=200, verbose_name='Hero Subtitle'),
        ),
        migrations.AlterField(
            model_name='homepagesettings',
            name='hero_title',
            field=models.CharField(default='Guiding your Success, Every step of the way!', max_length=200, verbose_name='Hero Title'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='company_phone',
            field=models.CharField(blank=True, max_length=50, verbose_name='Company Phone'),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='role',
            field=models.CharField(choices=[('founder', 'Founder & Manager'), ('deputy_manager', 'Deputy Manager'), ('associate_trainer', 'Associate Trainer'), ('consultant', 'Consultant'), ('sales_officer', 'Sales Officer'), ('sales_agent', 'Sales Agent'), ('other', 'Other')], max_length=20),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='years_experience',
            field=models.IntegerField(default=0, help_text='Years of professional experience', verbose_name='Years of Experience'),
        ),
        migrations.CreateModel(
            name='CaseStudyTimeline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('date', models.DateField(verbose_name='Date')),
                ('order', models.IntegerField(default=0, verbose_name='Order')),
                ('case_study', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timeline', to='properties.casestudy')),
            ],
            options={
                'verbose_name': 'Case Study Timeline',
                'verbose_name_plural': 'Case Study Timelines',
                'ordering': ['order', 'date'],
            },
        ),
        migrations.CreateModel(
            name='MediaItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='Title')),
                ('media_type', models.CharField(choices=[('image', 'Image'), ('video', 'Video')], default='image', max_length=10)),
                ('image', models.ImageField(blank=True, null=True, upload_to='gallery/', verbose_name='Image')),
                ('video_url', models.URLField(blank=True, verbose_name='Video URL')),
                ('caption', models.CharField(blank=True, max_length=300, verbose_name='Caption')),
                ('order', models.IntegerField(default=0, verbose_name='Order')),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='properties.mediaalbum')),
            ],
            options={
                'verbose_name': 'Media Item',
                'verbose_name_plural': 'Media Items',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='EventRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200, verbose_name='Full Name')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone', models.CharField(max_length=30, verbose_name='Phone')),
                ('organization', models.CharField(blank=True, max_length=200, verbose_name='Organization')),
                ('job_title', models.CharField(blank=True, max_length=200, verbose_name='Job Title')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='properties.trainingevent')),
            ],
            options={
                'verbose_name': 'Event Registration',
                'verbose_name_plural': 'Event Registrations',
                'ordering': ['-created_at'],
            },
        ),
    ]
