# Generated by Django 5.2.9 on 2026-06-12 12:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0015_casestudy_mediaalbum_milestone_partner_service_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediaitem',
            name='video_file',
            field=models.FileField(blank=True, help_text='MP4 or WebM video upload', null=True, upload_to='gallery/videos/', verbose_name='Video File'),
        ),
        migrations.AlterField(
            model_name='mediaitem',
            name='image',
            field=models.ImageField(blank=True, help_text='Recommended: 1200×800px or larger, JPG/PNG/WebP', null=True, upload_to='gallery/images/', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='mediaitem',
            name='video_url',
            field=models.URLField(blank=True, help_text='YouTube or Vimeo link (alternative to uploaded video)', verbose_name='Video URL'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='whatsapp_default_message',
            field=models.CharField(default='Hello! I am interested in your training and consultancy services.', help_text='Default message for WhatsApp inquiries', max_length=500, verbose_name='Default WhatsApp Message'),
        ),
        migrations.CreateModel(
            name='CaseStudyMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='Title')),
                ('media_type', models.CharField(choices=[('image', 'Image'), ('video', 'Video')], default='image', max_length=10)),
                ('image', models.ImageField(blank=True, null=True, upload_to='case_studies/gallery/', verbose_name='Image')),
                ('video_file', models.FileField(blank=True, null=True, upload_to='case_studies/videos/', verbose_name='Video File')),
                ('video_url', models.URLField(blank=True, verbose_name='Video URL')),
                ('caption', models.CharField(blank=True, max_length=300, verbose_name='Caption')),
                ('order', models.IntegerField(default=0, verbose_name='Order')),
                ('case_study', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media_items', to='properties.casestudy')),
            ],
            options={
                'verbose_name': 'Case Study Media',
                'verbose_name_plural': 'Case Study Media',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='EventMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='Title')),
                ('media_type', models.CharField(choices=[('image', 'Image'), ('video', 'Video')], default='image', max_length=10)),
                ('image', models.ImageField(blank=True, null=True, upload_to='events/gallery/', verbose_name='Image')),
                ('video_file', models.FileField(blank=True, null=True, upload_to='events/videos/', verbose_name='Video File')),
                ('video_url', models.URLField(blank=True, verbose_name='Video URL')),
                ('caption', models.CharField(blank=True, max_length=300, verbose_name='Caption')),
                ('order', models.IntegerField(default=0, verbose_name='Order')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media_items', to='properties.trainingevent')),
            ],
            options={
                'verbose_name': 'Event Media',
                'verbose_name_plural': 'Event Media',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ServiceMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='Title')),
                ('media_type', models.CharField(choices=[('image', 'Image'), ('video', 'Video')], default='image', max_length=10)),
                ('image', models.ImageField(blank=True, null=True, upload_to='services/gallery/', verbose_name='Image')),
                ('video_file', models.FileField(blank=True, null=True, upload_to='services/videos/', verbose_name='Video File')),
                ('video_url', models.URLField(blank=True, verbose_name='Video URL')),
                ('caption', models.CharField(blank=True, max_length=300, verbose_name='Caption')),
                ('order', models.IntegerField(default=0, verbose_name='Order')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media_items', to='properties.service')),
            ],
            options={
                'verbose_name': 'Service Media',
                'verbose_name_plural': 'Service Media',
                'ordering': ['order'],
            },
        ),
    ]
