# Generated by Django 5.2.8 on 2026-06-26 06:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0019_eventregistration_gdpr_consent'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug')),
                ('department', models.CharField(blank=True, max_length=100, verbose_name='Department')),
                ('location', models.CharField(blank=True, max_length=200, verbose_name='Location')),
                ('employment_type', models.CharField(choices=[('full_time', 'Full Time'), ('part_time', 'Part Time'), ('contract', 'Contract'), ('internship', 'Internship')], default='full_time', max_length=20, verbose_name='Employment Type')),
                ('description', models.TextField(verbose_name='Description')),
                ('short_description', models.TextField(blank=True, max_length=500, verbose_name='Short Description')),
                ('requirements', models.TextField(blank=True, verbose_name='Requirements')),
                ('application_open_at', models.DateTimeField(blank=True, help_text='Leave blank to open applications immediately when published.', null=True, verbose_name='Application Opens')),
                ('application_deadline', models.DateTimeField(blank=True, help_text='Leave blank for no deadline.', null=True, verbose_name='Application Deadline')),
                ('max_applications', models.PositiveIntegerField(default=0, help_text='0 means unlimited.', verbose_name='Max Applications')),
                ('is_published', models.BooleanField(default=True, verbose_name='Published')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Featured')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Vacancy',
                'verbose_name_plural': 'Vacancies',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='is_verified',
            field=models.BooleanField(default=False, help_text='Mark team member as verified', verbose_name='Verified'),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='role',
            field=models.CharField(choices=[('founder', 'Founder & Manager'), ('deputy_manager', 'Deputy Manager'), ('associate_trainer', 'Associate Trainer'), ('consultant', 'Consultant'), ('sales_officer', 'Sales Officer'), ('sales_agent', 'Business Development Officer'), ('other', 'Other')], max_length=20),
        ),
        migrations.CreateModel(
            name='VacancyApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200, verbose_name='Full Name')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone', models.CharField(max_length=30, verbose_name='Phone')),
                ('education', models.CharField(blank=True, max_length=200, verbose_name='Education')),
                ('years_experience', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Years of Experience')),
                ('cover_letter', models.TextField(blank=True, verbose_name='Cover Letter')),
                ('resume', models.FileField(blank=True, help_text='PDF, DOC, or DOCX (max 5 MB).', null=True, upload_to='vacancy_applications/', verbose_name='Resume / CV')),
                ('gdpr_consent', models.BooleanField(default=False, verbose_name='Privacy Consent')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('reviewed', 'Reviewed'), ('shortlisted', 'Shortlisted'), ('rejected', 'Rejected'), ('withdrawn', 'Withdrawn')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('vacancy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='properties.vacancy')),
            ],
            options={
                'verbose_name': 'Vacancy Application',
                'verbose_name_plural': 'Vacancy Applications',
                'ordering': ['-created_at'],
            },
        ),
    ]
